
//User_Bookmarks
export const USER_BOOKMARKS_REQUEST = 'USER_BOOKMARKS_REQUEST';
export const USER_BOOKMARKS_SUCCESS = 'USER_BOOKMARKS_SUCCESS';
export const USER_BOOKMARKS_ERROR = 'USER_BOOKMARKS_ERROR';