export const ARTICLE_MOST_READ_REQUEST = 'ARTICLE_MOST_READ_REQUEST';
export const ARTICLE_MOST_READ_SUCCESS = 'ARTICLE_MOST_READ_SUCCESS';
export const ARTICLE_MOST_READ_ERROR = 'ARTICLE_MOST_READ_ERROR';