export const DAILY_SOURCE_STATISTICS_REQUEST = 'DAILY_SOURCE_STATISTICS_REQUEST';
export const DAILY_SOURCE_STATISTICS_SUCCESS = 'DAILY_SOURCE_STATISTICS_SUCCESS';
export const DAILY_SOURCE_STATISTICS_ERROR = 'DAILY_SOURCE_STATISTICS_ERROR';